### ISSUE TITLE
Plugin installation was unsuccessful

### ISSUE THREAD

**Issue by yhgcn** [Oxalide/kibana_metric_vis_colors#1]
/opt/kibana # bin/kibana plugin --install metric-vis-colors -u file:///opt/kibana/src/plugins/kibana_metric_vis_colors.zip 
Installing metric-vis-colors
Attempting to transfer from file:///opt/kibana/src/plugins/kibana_metric_vis_colors.zip
Transferring 38433 bytes....................
Transfer complete
Extracting plugin archive
Extraction complete
Optimizing and caching browser bundles...
Plugin installation was unsuccessful due to error "Config schema already has key: metric_vis_colors"

/opt/kibana # ll installedPlugins
total 48
drwxr-xr-x 12  501 staff 4096 Jun 19 12:55 ./
drwxr-xr-x 10  501 staff 4096 May  5 01:16 ../
drwxr-xr-x  5 root root  4096 May  5 02:39 graph/
drwxr-xr-x  3 root root  4096 May  5 02:33 heatmap/
drwxr-xr-x  7 root root  4096 May  5 03:00 kbn_sankey_vis/
drwxr-xr-x  6 root root  4096 May  5 02:33 sense/
drwxr-xr-x  3 root root  4096 May  5 02:33 tagcloud/
drwxr-xr-x 10 root root  4096 May  5 02:33 timelion/
drwxr-xr-x  3 root root  4096 May  5 02:33 vectormap/
===>root – 172.17.0.2 – /opt/kibana\

**Comment by aksbhatia** [comment]
I am getting the same too...
Plugin installation was unsuccessful due to error "Config schema already has key: metric_vis_colors"

I tried manually removing the enty from some ./optimize/.babelcache.json file too.
Nothing helped.

**Comment by valouille** [comment]
Which version of Kibana are you using ?

**Comment by aksbhatia** [comment]
4.5.1
kibana-4.5.1-linux-x64

**Comment by aksbhatia** [comment]
FATAL [Error: Config schema already has key: metric_vis_colors]
{"type":"log","@timestamp":"2016-06-24T05:37:36+00:00","tags":["fatal"],"pid":1864,"level":"fatal","message":"Config schema already has key: metric_vis_colors","error":{"message":"Config schema already has key: metric_vis_colors","name":"Error","stack":"Error: Config schema already has key: metric_vis_colors\n    at Config.extendSchema (/home/aksbhatia/elastic/kibana-4.5.1-linux-x64/src/server/config/config.js:61:15)\n    at ScopedPlugin.readConfig$ (/home/aksbhatia/elastic/kibana-4.5.1-linux-x64/src/server/plugins/Plugin.js:68:20)\n    at tryCatch (/home/aksbhatia/elastic/kibana-4.5.1-linux-x64/node_modules/babel-runtime/regenerator/runtime.js:67:40)\n

**Comment by aksbhatia** [comment]
@valouille did you check on this?

**Comment by userBD** [comment]
Hi all,

Same here, i can't install the plugin

![image](https://cloud.githubusercontent.com/assets/19348221/16488062/ca64a608-3ece-11e6-9998-030e7bd2ea55.png)

Someone know what to do to overcome ?

Thx all

**Comment by valouille** [comment]
Hello,

The problem was the installation process. We should not clone the repository in $KIBANA_HOME/src/plugins.
So the fix is to remove it from this directory, and install it from another:

```
rm -rf $KIBANA_HOME/src/plugins/kibana_metric_vis_colors*
cd ~
git clone https://github.com/Oxalide/kibana_metric_vis_colors.git
zip -r kibana_metric_vis_colors kibana_metric_vis_colors
$KIBANA_HOME/bin/kibana plugin --install metric_vis_color -u file:///$HOME_DIR/kibana_metric_vis_colors.zip
```

I will update the installation process 

VaLouille
