### ISSUE TITLE
Support for Kibana 5

### ISSUE THREAD

**Issue by acommendador** [Oxalide/kibana_metric_vis_colors#3]
Attempted to install the plugin using Kibana 5 alpha 5 and received the following error:
...
Transferring 39993 bytes....................
Transfer complete
Retrieving metadata from plugin archive
Plugin installation was unsuccessful due to error "No kibana plugins found in archive"

**Comment by acommendador** [comment]
Found a way to get this to work. For Kibana 5 the plugin must be added to an empty "kibana" directory (see kibana/src/cli_plugin/install/pack.js).  Additionally, the package.json version must match the kibana version.

**Comment by nreese** [comment]
How did you get this to work? Could you please provide more information?

**Comment by acommendador** [comment]
It wasn't as simple as I made it out to be.  The javascript files needed to be modified to get this to work.  Here is the source (downloaded 10/27/2016) with the modifications.

[kibana.zip](https://github.com/Oxalide/kibana_metric_vis_colors/files/557485/kibana.zip)

You should be able to run bin/kibana-plugin.bat install file:///<path to downloaded kibana.zip> (omit the C:/ if on windows).  To remove the plug-in run bin/kibana-plugin.bat remove metric_vis_colors

**Comment by calston** [comment]
Could you put that in a PR so people can see it sensibly?
